### ISSUE TITLE
PollController getAllPolls()

### ISSUE THREAD

**Issue by ImGoze** [spydx/dat250gruppe9#4]
**SECURITY BREACH:** It returns the users password

**Comment by spydx** [comment]
Updated in Commit : 
commit d1d448226fb10be0876e2f964860badd3e98b96a (HEAD -> RESTful-web-API, origin/RESTful-web-API)
Author: Kenneth <fossen.kenneth@gmail.com>
Date:   Sun Oct 4 23:00:40 2020 +0200

    Password Issue in User Model


Query the rest API and this is the result:


{
  "id": 607,
  "firstname": "user 6",
  "lastname": null,
  "email": "user6@mail.com",
  **_"password": null,_**
  "role": "USER",
  "pollsList": [],
  "votedOn": [
    {
      "id": 628,
      "voterid": 607,
      "answer": true,
      "votetime": "2020-10-04T17:24:23.437+00:00"
    }
  ]
}
